# Override logging settings to LogServer
version: "3.7"

x-logging:
  &default-logging
  driver: "gelf"
  options:
    gelf-address: "udp://127.0.0.1:12201"

services:
  youtubelivechattodiscord_Tama:
    logging: *default-logging
  youtubelivechattodiscord_Tama_mem:
    logging: *default-logging
  youtubelivechattodiscord_Yuna:
    logging: *default-logging
  youtubelivechattodiscord_Kakeru:
    logging: *default-logging
  youtubelivechattodiscord_Kakeru_mem:
    logging: *default-logging
  youtubelivechattodiscord_Emurii:
    logging: *default-logging
  youtubelivechattodiscord_Ruri:
    logging: *default-logging
  youtubelivechattodiscord_Aruma:
    logging: *default-logging
  youtubelivechattodiscord_Aruma_mem:
    logging: *default-logging
  youtubelivechattodiscord_Eri:
    logging: *default-logging

