version: '3.7'

x-labels:
  labels: &default-label
    youtubelivechattodiscord:
services:
  youtubelivechattodiscord:
    image: ghcr.io/jim60105/youtubelivechattodiscord
    # build: .
    labels: *default-label
    restart: unless-stopped
    # Youtube videoId, discord webhook url
    command: ["", ""]

  # # Restart main container every 4 hours.
  # jobber:
  #   image: blacklabelops/jobber:docker
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     - JOB_NAME1=restart
  #     - JOB_COMMAND1=docker restart $$(docker ps -aqf "label=youtubelivechattodiscord")
  #     - JOB_TIME1=* * */4 * * * #Every 4 hours
  #     - JOB_NOTIFY_ERR1=false
  #     - JOB_NOTIFY_FAIL1=false