{{- range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "youtube-live-chat-to-discord.fullname" $ }}-{{ .name }}
  labels:
    {{- include "youtube-live-chat-to-discord.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
    {{- include "youtube-live-chat-to-discord.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .name }}
      {{- include "youtube-live-chat-to-discord.selectorLabels" $ | nindent 8 }}
    spec:
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .name }}
          args:
          - {{ quote .youtubeId }}
          - {{ quote .discordWebhook }}
          env:
          - name: KUBERNETES_CLUSTER_DOMAIN
            value: {{ quote $.Values.kubernetesClusterDomain }}
          - name: Logging__LogLevel__Default
            value: Debug
          image: ghcr.io/jim60105/youtubelivechattodiscord:latest
          resources: 
            limits:
              memory: "512Mi"
              cpu: "100m"
            requests:
              memory: "256Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: "RuntimeDefault"
            runAsUser: 1654
            runAsGroup: 1654
{{- if .useCookies }}
          volumeMounts:
          - mountPath: /app/cookies.txt
            name: cookies
            subPath: cookies.txt
      volumes:
      - name: cookies
        configMap:
          name: {{ include "youtube-live-chat-to-discord.fullname" $ }}-cookies
{{- end }}
{{- end }}